(cl:in-package test_opencv-msg)
(cl:export '(TIME-VAL
          TIME
          EULERHEADING-VAL
          EULERHEADING
          EULERROLL-VAL
          EULERROLL
          ACCELEROMETERX-VAL
          ACCELEROMETERX
          ACCELEROMETERY-VAL
          ACCELEROMETERY
          ACCELEROMETERZ-VAL
          ACCELEROMETERZ
          LINEARACCELERX-VAL
          LINEARACCELERX
          LINEARACCELERY-VAL
          LINEARACCELERY
          LINEARACCELERZ-VAL
          LINEARACCELERZ
          GRAVACCELERX-VAL
          GRAVACCELERX
          GRAVACCELERY-VAL
          GRAVACCELERY
          GRAVACCELERZ-VAL
          GRAVACCELERZ
          EULERPITCH-VAL
          EULERPITCH
))